-- IPTVCloud Database Initialization

-- 0. Custom Types
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('user', 'moderator', 'admin');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE theme_mode_type AS ENUM ('light', 'dark', 'system');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE player_resolution_type AS ENUM ('default', '1080p', '720p', '480p');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    middle_initial TEXT,
    last_name TEXT,
    suffix TEXT,
    birthday DATE, -- Added for 13+ check
    role user_role DEFAULT 'user',
    is_verified BOOLEAN DEFAULT false,
    avatar_url TEXT,
    suspended_until TIMESTAMPTZ, -- For admin moderation
    is_muted BOOLEAN DEFAULT false, -- For admin moderation
    is_restricted BOOLEAN DEFAULT false, -- Shadow ban
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Auth Codes (OTP) Table
CREATE TABLE IF NOT EXISTS auth_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    code TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('login', 'reset', 'verify_email', 'change_username')),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(email, type)
);

-- 3. Channel Mappings Table
CREATE TABLE IF NOT EXISTS channel_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_id TEXT UNIQUE NOT NULL,
    short_id TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. User Settings Table
CREATE TABLE IF NOT EXISTS user_settings (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    theme_mode theme_mode_type DEFAULT 'system',
    theme_accent TEXT DEFAULT '#5e6ad2',
    player_resolution player_resolution_type DEFAULT 'default',
    player_cc BOOLEAN DEFAULT false,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. User Privacy Table
CREATE TABLE IF NOT EXISTS user_privacy (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    show_followers BOOLEAN DEFAULT true,
    show_following BOOLEAN DEFAULT true,
    show_watch_history BOOLEAN DEFAULT true,
    show_comments BOOLEAN DEFAULT true,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Followers Table
CREATE TABLE IF NOT EXISTS followers (
    follower_id UUID REFERENCES users(id) ON DELETE CASCADE,
    following_id UUID REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (follower_id, following_id)
);

-- 7. Favorites Table
CREATE TABLE IF NOT EXISTS favorites (
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    channel_short_id TEXT REFERENCES channel_mappings(short_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, channel_short_id)
);

-- 8. Watch History Table
CREATE TABLE IF NOT EXISTS watch_history (
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    channel_short_id TEXT REFERENCES channel_mappings(short_id) ON DELETE CASCADE,
    last_watched_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, channel_short_id)
);

-- 9. 2FA Secrets Table
CREATE TABLE IF NOT EXISTS two_factor_secrets (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    secret TEXT NOT NULL,
    is_enabled BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Live Comments Table
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    channel_short_id TEXT REFERENCES channel_mappings(short_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    is_pinned BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Analytics/Logs (Simple)
CREATE TABLE IF NOT EXISTS site_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    event_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Playlists Table
CREATE TABLE IF NOT EXISTS playlists (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    is_public BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. Playlist Items Table
CREATE TABLE IF NOT EXISTS playlist_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    playlist_id UUID REFERENCES playlists(id) ON DELETE CASCADE,
    channel_short_id TEXT REFERENCES channel_mappings(short_id) ON DELETE CASCADE,
    position_order INTEGER NOT NULL DEFAULT 0,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(playlist_id, channel_short_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_auth_codes_email_type ON auth_codes(email, type);
CREATE INDEX IF NOT EXISTS idx_channel_mappings_short_id ON channel_mappings(short_id);
CREATE INDEX IF NOT EXISTS idx_followers_following_id ON followers(following_id);
CREATE INDEX IF NOT EXISTS idx_watch_history_user_id ON watch_history(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_channel_id ON comments(channel_short_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);
CREATE INDEX IF NOT EXISTS idx_site_analytics_event_type ON site_analytics(event_type);
CREATE INDEX IF NOT EXISTS idx_playlists_user_id ON playlists(user_id);
CREATE INDEX IF NOT EXISTS idx_playlist_items_playlist_id ON playlist_items(playlist_id);

-- 14. IPTV Metadata Tables
CREATE TABLE IF NOT EXISTS iptv_countries (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    flag TEXT,
    region TEXT
);

CREATE TABLE IF NOT EXISTS iptv_categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iptv_languages (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iptv_channels (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    logo TEXT,
    country TEXT REFERENCES iptv_countries(code),
    subdivision TEXT,
    city TEXT,
    broadcast_area TEXT[],
    categories TEXT[],
    languages TEXT[],
    is_nsfw BOOLEAN DEFAULT false,
    website TEXT,
    network TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS iptv_streams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id TEXT REFERENCES iptv_channels(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    timeshift TEXT,
    http_referrer TEXT,
    user_agent TEXT,
    status TEXT DEFAULT 'unknown',
    last_checked_at TIMESTAMPTZ DEFAULT NOW(),
    quality TEXT,
    width INTEGER,
    height INTEGER,
    UNIQUE(channel_id, url)
);

-- Indexes for fast filtering
CREATE INDEX IF NOT EXISTS idx_iptv_channels_country ON iptv_channels(country);
CREATE INDEX IF NOT EXISTS idx_iptv_channels_categories ON iptv_channels USING GIN (categories);
CREATE INDEX IF NOT EXISTS idx_iptv_channels_languages ON iptv_channels USING GIN (languages);
CREATE INDEX IF NOT EXISTS idx_iptv_streams_channel_id ON iptv_streams(channel_id);
CREATE INDEX IF NOT EXISTS idx_iptv_streams_status ON iptv_streams(status);